menu:
  Home: /
  Archives: archives
  page:
    About: about

excerpt_link: Continue →

mathjax: true
fancybox: true

social:
  twitter: true
  github: true
  rss: true

twitter:
  username: postwait

github:
  username: postwait

addit:
  facebook: true
  twitter: true
  gplus: true
  pinit: false
  publid:
