menu:
  Home: /
  Archives: archives
  page:
    About: about/
    Speaking: speaks/

excerpt_link: Continue →

mathjax: true
fancybox: true

google_analytics: UA-1004645-1

social:
  twitter: true
  github: true
  rss: true

twitter:
  username: postwait

github:
  username: postwait

addit:
  facebook: true
  twitter: true
  gplus: true
  pinit: false
  publid:
